www----dddbbbkkkxxxddd

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -39,18 +39,16 @@ cd ../
 rm -fv env-${ENV}/.terraform/terraform.tfstate
 chmod 755 setup_remote_state.sh
 ./setup_remote_state.sh
-
 cd env-${ENV}
 terraform ${TERRAFORM_COMMAND} -no-color -auto-approve
+if [ currentBuild.currentResult == 'SUCCESS' ]; then
+slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
+elseif [ currentBuild.currentResult == 'FAILURE' ]; then
+slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
+else
+exit 1
+fi
 '''
 }
 }
-stage ('success') {
-      if(currentBuild.currentResult == 'SUCCESS') {
-      slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
-      }
-      else if ((currentBuild.currentResult == 'FAILURE') && buildChanged) {
-      slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
-      }
-    }
-  }
+}
